modLoader="javafml"

loaderVersion="43.4.4"

license="MIT"

[[mods]]
modId="farcraft"
version="0.0.1-1.19.2"
displayName="Farcraft: The Mod"
authors="jiv007"
description="A progression and flavoring mod for the Farcraft SMP."

